---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling.stefaniak.dev
  resources:
  - startupcpuboosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.stefaniak.dev
  resources:
  - startupcpuboosts/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.stefaniak.dev
  resources:
  - startupcpuboosts/status
  verbs:
  - get
  - patch
  - update
