# permissions for end users to edit startupcpuboosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: startupcpuboost-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-startup-cpu-boost
    app.kubernetes.io/part-of: kube-startup-cpu-boost
    app.kubernetes.io/managed-by: kustomize
  name: startupcpuboost-editor-role
rules:
- apiGroups:
  - autoscaling.stefaniak.dev
  resources:
  - startupcpuboosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.stefaniak.dev
  resources:
  - startupcpuboosts/status
  verbs:
  - get
