apiVersion: autoscaling.stefaniak.dev/v1alpha1
kind: StartupCPUBoost
metadata:
  name: boost-001
  namespace: demo
selector:
  matchExpressions:
  - key: app
    operator: In
    values: ["app-001", "whereami"]
spec:
  timePeriod: 60
  boostPercent: 50
