apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: demo
  labels:
    app: app-001
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
