apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.19
        env:
        - name: METADATA
          value: "default-backend"
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
